import java.awt.Container;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;


public class interfaz extends javax.swing.JFrame {
        
    public interfaz() {
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/img/fondo.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        bGuardar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l14 = new javax.swing.JLabel();
        l15 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l17 = new javax.swing.JLabel();
        l18 = new javax.swing.JLabel();
        l19 = new javax.swing.JLabel();
        l20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b1.setText("CARA");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setText("OJOS");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setText("NARIZ");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setText("BOCA");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setText("OREJAS");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        l2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                l2MouseDragged(evt);
            }
        });

        l3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                l3MouseDragged(evt);
            }
        });

        l4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                l4MouseDragged(evt);
            }
        });

        l5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                l5MouseDragged(evt);
            }
        });

        l6.setBorder(new javax.swing.border.MatteBorder(null));
        l6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                l6MouseDragged(evt);
            }
        });

        bGuardar.setText("GUARDAR");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        bSalir.setText("SALIR");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        l1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                l1MouseDragged(evt);
            }
        });

        l7.setBorder(new javax.swing.border.MatteBorder(null));
        l7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                l7MouseDragged(evt);
            }
        });

        l8.setBorder(new javax.swing.border.MatteBorder(null));
        l8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                l8MouseDragged(evt);
            }
        });

        l9.setBorder(new javax.swing.border.MatteBorder(null));
        l9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                l9MouseDragged(evt);
            }
        });

        l12.setBorder(new javax.swing.border.MatteBorder(null));
        l12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                l12MouseDragged(evt);
            }
        });

        l13.setBorder(new javax.swing.border.MatteBorder(null));
        l13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                l13MouseDragged(evt);
            }
        });

        l14.setBorder(new javax.swing.border.MatteBorder(null));
        l14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                l14MouseDragged(evt);
            }
        });

        l15.setBorder(new javax.swing.border.MatteBorder(null));
        l15.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                l15MouseDragged(evt);
            }
        });

        l10.setBorder(new javax.swing.border.MatteBorder(null));
        l10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                l10MouseDragged(evt);
            }
        });

        l17.setBorder(new javax.swing.border.MatteBorder(null));
        l17.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                l17MouseDragged(evt);
            }
        });

        l18.setBorder(new javax.swing.border.MatteBorder(null));
        l18.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                l18MouseDragged(evt);
            }
        });

        l19.setBorder(new javax.swing.border.MatteBorder(null));
        l19.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                l19MouseDragged(evt);
            }
        });

        l20.setBorder(new javax.swing.border.MatteBorder(null));
        l20.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                l20MouseDragged(evt);
            }
        });

        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(b4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(bSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(l8, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                        .addComponent(l10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(l14, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(l15, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(l6, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                        .addComponent(l7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(l12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(l20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(l5, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                        .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(l17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(l11)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b1)
                            .addComponent(l3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(l2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(l6, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                    .addComponent(l5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(l9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(l7, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b2)
                                .addGap(91, 91, 91)
                                .addComponent(b3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(l8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(l12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(l13, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(l10, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l14, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5)
                            .addComponent(l15, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l18, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l17, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l19, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l20, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(29, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGuardar)
                    .addComponent(bSalir))
                .addGap(99, 99, 99))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 418, Short.MAX_VALUE)
                    .addComponent(l11)
                    .addGap(0, 418, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        Container container = getContentPane();
        container.setLayout(null);
        
        ImageIcon c1 = new ImageIcon(getClass().getResource("/img/cara 1.jpg"));
        ImageIcon icono1 = new ImageIcon(c1.getImage().getScaledInstance(l1.getWidth(), l1.getHeight(), Image.SCALE_DEFAULT));
        l1.setIcon(icono1);
        container.add(l1);
        
        ImageIcon c2 = new ImageIcon(getClass().getResource("/img/cara 2.jpg"));
        ImageIcon icono2 = new ImageIcon(c2.getImage().getScaledInstance(l2.getWidth(), l2.getHeight(), Image.SCALE_DEFAULT));
        l2.setIcon(icono2);
        container.add(l2);
        
        ImageIcon c3 = new ImageIcon(getClass().getResource("/img/cara 3.png"));
        ImageIcon icono3 = new ImageIcon(c3.getImage().getScaledInstance(l3.getWidth(), l3.getHeight(), Image.SCALE_DEFAULT));
        l3.setIcon(icono3);
        container.add(l3);
    }//GEN-LAST:event_b1ActionPerformed
    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        Container container = getContentPane();
        container.setLayout(null);
        ImageIcon ic1 = new ImageIcon(getClass().getResource("/img/ojos 1.jpg"));
        ImageIcon icono = new ImageIcon(ic1.getImage().getScaledInstance(l4.getWidth(), l4.getHeight(), Image.SCALE_DEFAULT));
        l4.setIcon(icono);
        container.add(l4);
        
        ImageIcon ic2 = new ImageIcon(getClass().getResource("/img/ojos.jpg"));
        ImageIcon icono1 = new ImageIcon(ic2.getImage().getScaledInstance(l5.getWidth(), l5.getHeight(), Image.SCALE_DEFAULT));
        l5.setIcon(icono1);
        container.add(l5);
        
        ImageIcon ic3 = new ImageIcon(getClass().getResource("/img/ojos 3.jpg"));
        ImageIcon icono2 = new ImageIcon(ic3.getImage().getScaledInstance(l6.getWidth(), l6.getHeight(), Image.SCALE_DEFAULT));
        l6.setIcon(icono2);
        container.add(l6);
    }//GEN-LAST:event_b2ActionPerformed

    private void l2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseDragged
        l2.setLocation(
				l2.getX() + evt.getX() - l2.getWidth() / 2,
 				l2.getY() + evt.getY() - l2.getHeight() / 2
				);
    }//GEN-LAST:event_l2MouseDragged

    private void l3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseDragged
        l3.setLocation(
				l3.getX() + evt.getX() - l3.getWidth() / 2,
 				l3.getY() + evt.getY() - l3.getHeight() / 2
				);
    }//GEN-LAST:event_l3MouseDragged

    private void l4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseDragged
        l4.setLocation(
				l4.getX() + evt.getX() - l4.getWidth() / 2,
 				l4.getY() + evt.getY() - l4.getHeight() / 2
				);
    }//GEN-LAST:event_l4MouseDragged

    private void l5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l5MouseDragged
        l5.setLocation(
				l5.getX() + evt.getX() - l5.getWidth() / 2,
 				l5.getY() + evt.getY() - l5.getHeight() / 2
				);
    }//GEN-LAST:event_l5MouseDragged

    private void l6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l6MouseDragged
        l6.setLocation(
				l6.getX() + evt.getX() - l6.getWidth() / 2,
 				l6.getY() + evt.getY() - l6.getHeight() / 2
				);
    }//GEN-LAST:event_l6MouseDragged

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void l1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseDragged
        l1.setLocation(
				l1.getX() + evt.getX() - l1.getWidth() / 2,
 				l1.getY() + evt.getY() - l1.getHeight() / 2
				);
    }//GEN-LAST:event_l1MouseDragged

    private void l7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l7MouseDragged
        l7.setLocation(
				l7.getX() + evt.getX() - l7.getWidth() / 2,
 				l7.getY() + evt.getY() - l7.getHeight() / 2
				);
    }//GEN-LAST:event_l7MouseDragged

    private void l8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MouseDragged
        l8.setLocation(
				l8.getX() + evt.getX() - l8.getWidth() / 2,
 				l8.getY() + evt.getY() - l8.getHeight() / 2
				);
    }//GEN-LAST:event_l8MouseDragged

    private void l9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l9MouseDragged
        l9.setLocation(
				l9.getX() + evt.getX() - l9.getWidth() / 2,
 				l9.getY() + evt.getY() - l9.getHeight() / 2
				);
    }//GEN-LAST:event_l9MouseDragged

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        Container container = getContentPane();
        container.setLayout(null);
        ImageIcon ic1 = new ImageIcon(getClass().getResource("/img/nariz 1.jpg"));
        ImageIcon icono = new ImageIcon(ic1.getImage().getScaledInstance(l7.getWidth(), l7.getHeight(), Image.SCALE_DEFAULT));
        l7.setIcon(icono);
        container.add(l7);
        
        ImageIcon ic2 = new ImageIcon(getClass().getResource("/img/nariz 2.jpg"));
        ImageIcon icono1 = new ImageIcon(ic2.getImage().getScaledInstance(l8.getWidth(), l8.getHeight(), Image.SCALE_DEFAULT));
        l8.setIcon(icono1);
        container.add(l8);
        
        ImageIcon ic3 = new ImageIcon(getClass().getResource("/img/nariz 3.jpg"));
        ImageIcon icono2 = new ImageIcon(ic3.getImage().getScaledInstance(l9.getWidth(), l9.getHeight(), Image.SCALE_DEFAULT));
        l9.setIcon(icono2);
        container.add(l9);
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        Container container = getContentPane();
        container.setLayout(null);
        ImageIcon ic1 = new ImageIcon(getClass().getResource("/img/boca.png"));
        ImageIcon icono = new ImageIcon(ic1.getImage().getScaledInstance(l10.getWidth(), l10.getHeight(), Image.SCALE_DEFAULT));
        l10.setIcon(icono);
        container.add(l10);
        
        ImageIcon ic2 = new ImageIcon(getClass().getResource("/img/boca 1.jpg"));
        ImageIcon icono1 = new ImageIcon(ic2.getImage().getScaledInstance(l12.getWidth(), l12.getHeight(), Image.SCALE_DEFAULT));
        l12.setIcon(icono1);
        container.add(l12);
        
        ImageIcon ic3 = new ImageIcon(getClass().getResource("/img/boca 2.jpg"));
        ImageIcon icono2 = new ImageIcon(ic3.getImage().getScaledInstance(l13.getWidth(), l13.getHeight(), Image.SCALE_DEFAULT));
        l13.setIcon(icono2);
        container.add(l13);
    }//GEN-LAST:event_b4ActionPerformed

    private void l10MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l10MouseDragged
        l10.setLocation(
				l10.getX() + evt.getX() - l10.getWidth() / 2,
 				l10.getY() + evt.getY() - l10.getHeight() / 2
				);
    }//GEN-LAST:event_l10MouseDragged

    private void l12MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l12MouseDragged
        l12.setLocation(
				l12.getX() + evt.getX() - l12.getWidth() / 2,
 				l12.getY() + evt.getY() - l12.getHeight() / 2
				);
    }//GEN-LAST:event_l12MouseDragged

    private void l13MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l13MouseDragged
        l13.setLocation(
				l13.getX() + evt.getX() - l13.getWidth() / 2,
 				l13.getY() + evt.getY() - l13.getHeight() / 2
				);
    }//GEN-LAST:event_l13MouseDragged

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        Container container = getContentPane();
        container.setLayout(null);
        ImageIcon ic1 = new ImageIcon(getClass().getResource("/img/oreja 1.1.jpg"));
        ImageIcon icono = new ImageIcon(ic1.getImage().getScaledInstance(l14.getWidth(), l14.getHeight(), Image.SCALE_DEFAULT));
        l14.setIcon(icono);
        container.add(l14);
        
        ImageIcon ic2 = new ImageIcon(getClass().getResource("/img/orejas 1.2.jpg"));
        ImageIcon icono1 = new ImageIcon(ic2.getImage().getScaledInstance(l15.getWidth(), l15.getHeight(), Image.SCALE_DEFAULT));
        l15.setIcon(icono1);
        container.add(l15);
        
        ImageIcon ic3 = new ImageIcon(getClass().getResource("/img/oreja 2.1.jpg"));
        ImageIcon icono2 = new ImageIcon(ic3.getImage().getScaledInstance(l20.getWidth(), l20.getHeight(), Image.SCALE_DEFAULT));
        l20.setIcon(icono2);
        container.add(l20);
        
        ImageIcon ic4 = new ImageIcon(getClass().getResource("/img/oreja 2.2.jpg"));
        ImageIcon icono3 = new ImageIcon(ic4.getImage().getScaledInstance(l19.getWidth(), l19.getHeight(), Image.SCALE_DEFAULT));
        l19.setIcon(icono3);
        container.add(l19);
        
        ImageIcon ic5 = new ImageIcon(getClass().getResource("/img/4.1.png"));
        ImageIcon icono4 = new ImageIcon(ic5.getImage().getScaledInstance(l18.getWidth(), l18.getHeight(), Image.SCALE_DEFAULT));
        l18.setIcon(icono4);
        container.add(l18);
        
        ImageIcon ic6 = new ImageIcon(getClass().getResource("/img/oreja 4.2.png"));
        ImageIcon icono5 = new ImageIcon(ic6.getImage().getScaledInstance(l17.getWidth(), l17.getHeight(), Image.SCALE_DEFAULT));
        l17.setIcon(icono5);
        container.add(l17);
        
    }//GEN-LAST:event_b5ActionPerformed

    private void l14MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l14MouseDragged
        l14.setLocation(
				l14.getX() + evt.getX() - l14.getWidth() / 2,
 				l14.getY() + evt.getY() - l14.getHeight() / 2
				);
    }//GEN-LAST:event_l14MouseDragged

    private void l15MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l15MouseDragged
        l15.setLocation(
				l15.getX() + evt.getX() - l15.getWidth() / 2,
 				l15.getY() + evt.getY() - l15.getHeight() / 2
				);
    }//GEN-LAST:event_l15MouseDragged

    private void l20MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l20MouseDragged
        l20.setLocation(
				l20.getX() + evt.getX() - l20.getWidth() / 2,
 				l20.getY() + evt.getY() - l20.getHeight() / 2
				);
    }//GEN-LAST:event_l20MouseDragged

    private void l19MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l19MouseDragged
       l19.setLocation(
				l19.getX() + evt.getX() - l19.getWidth() / 2,
 				l19.getY() + evt.getY() - l19.getHeight() / 2
				);
    }//GEN-LAST:event_l19MouseDragged

    private void l18MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l18MouseDragged
        l18.setLocation(
				l18.getX() + evt.getX() - l18.getWidth() / 2,
 				l18.getY() + evt.getY() - l18.getHeight() / 2
				);
    }//GEN-LAST:event_l18MouseDragged

    private void l17MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l17MouseDragged
        l17.setLocation(
				l17.getX() + evt.getX() - l17.getWidth() / 2,
 				l17.getY() + evt.getY() - l17.getHeight() / 2
				);
    }//GEN-LAST:event_l17MouseDragged

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        
    }//GEN-LAST:event_bGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l15;
    private javax.swing.JLabel l17;
    private javax.swing.JLabel l18;
    private javax.swing.JLabel l19;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l20;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    // End of variables declaration//GEN-END:variables

}
